title:              Vittorio Viti Portfolio
email:              vittorio.viti@studenti.unipr.it
description:        "And this, it's just the beginning of a wonderful journey"
author:             Start Bootstrap
baseurl:            "/vittaz.github.io"
url:                "https://vittaz.github.io"

# Social Profiles
twitter_username:   
github_username:    Vittaz
facebook_username:  vittorio.vintage.viti
instagram_username:  
linkedin_username: vittorio-viti

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
